package utils

import (
	"fmt"
	"math/rand/v2"

	"github.com/nbd-wtf/go-nostr"
)

// RandomEvents returns a slice of random events.
func RandomEvents() []nostr.Event {
	return RandomSlice(RandomEvent)
}

// RandomEvent returns a signed random event.
func RandomEvent() nostr.Event {
	event := nostr.Event{
		CreatedAt: nostr.Timestamp(rand.Int64()),
		Kind:      rand.Int(),
		Tags:      RandomTags(),
		Content:   RandomString(),
	}

	sk := nostr.GeneratePrivateKey()
	if err := event.Sign(sk); err != nil {
		panic(fmt.Errorf("failed to sign event: %w", err))
	}
	return event
}

// RandomFilters returns a slice of random filters.
func RandomFilters() nostr.Filters {
	return RandomSlice(RandomFilter)
}

// RandomFilter returns a random filter.
func RandomFilter() nostr.Filter {
	f := nostr.Filter{}
	if rand.Float32() < 0.2 {
		f.IDs = RandomSlice(RandomString)
	}
	if rand.Float32() < 0.2 {
		f.Kinds = RandomSlice(rand.Int)
	}
	if rand.Float32() < 0.2 {
		f.Authors = RandomSlice(RandomString)
	}
	if rand.Float32() < 0.2 {
		f.Tags = RandomTagMap()
	}
	if rand.Float32() < 0.2 {
		f.Since = RandomTimestamp()
	}
	if rand.Float32() < 0.2 {
		f.Until = RandomTimestamp()
	}
	if rand.Float32() < 0.2 {
		f.Limit = rand.Int()
	}
	if rand.Float32() < 0.2 {
		f.Search = RandomString()
	}
	return f
}

// RandomTagMap returns a random tag map to be used in filters.
func RandomTagMap() nostr.TagMap {
	size := rand.IntN(100)
	m := make(nostr.TagMap, size)
	for range size {
		m[RandomString()] = RandomTag()
	}
	return m
}

func RandomTags() []nostr.Tag {
	return RandomSlice(RandomTag)
}

// randomTag returns a random tag.
func RandomTag() nostr.Tag {
	l := rand.IntN(15)
	tag := make(nostr.Tag, l)
	for i := range l {
		tag[i] = RandomString()
	}
	return tag
}

// RandomSliceN returns a slice of n random elements generated by genFunc.
func RandomSliceN[T any](n int, genFunc func() T) []T {
	slice := make([]T, n)
	for i := range n {
		slice[i] = genFunc()
	}
	return slice
}

// RandomSlice returns a slice of random elements generated by genFunc.
func RandomSlice[T any](genFunc func() T) []T {
	n := int(rand.ExpFloat64() * 30)
	slice := make([]T, n)
	for i := range n {
		slice[i] = genFunc()
	}
	return slice
}

const symbols = `abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123456789`

// RandomString returns a random string of up to 70 characters.
func RandomString() string {
	l := rand.IntN(70)
	s := make([]byte, l)
	for i := range l {
		s[i] = symbols[rand.IntN(len(symbols))]
	}
	return string(s)
}

// RandomLetter returns a random letter.
func RandomLetter() string {
	return string(symbols[rand.IntN(len(symbols))])
}

// RandomTimestamp returns a random timestamp.
func RandomTimestamp() *nostr.Timestamp {
	timestamp := nostr.Timestamp(rand.Int64())
	return &timestamp
}
